batch

diff --git a/.dotfiles-bin/transcode-batch b/.dotfiles-bin/transcode-batch
--- a/.dotfiles-bin/transcode-batch
+++ b/.dotfiles-bin/transcode-batch
@@ -1,8 +1,57 @@
 #!/usr/bin/env bash
 
-readonly work="/Volumes/Data/makemkv"
+if [ -z "$TRANSCODE_BATCH_WORK_DIR" ]; then
+    echo "export \$TRANSCODE_BATCH_WORK_DIR must be set"
+    exit 1
+fi
+
+readonly work="$TRANSCODE_BATCH_WORK_DIR"
 readonly queue="$work/queue"
 readonly crops="$work/crops"
+
+readonly original="$1"
+readonly filename="$(basename "${original%.*}")"
+readonly cmd="$2"
+readonly option="$3"
+
+usage(){
+    echo "Usage:"
+    echo ""
+    echo "Start batch transcoding: $0"
+    echo ""
+    echo "Add file to batch queue: $0 \$file queue"
+    echo ""
+    echo "Add crop value for file: $0 \$file crop 140:140:0:0"
+    echo ""
+    exit 1
+}
+
+error(){
+    echo "Error: $1"
+    echo ""
+}
+
+if [ ! -z "$filename" ] && [ ! -f "$original" ]; then
+    error "$filename must exist"
+    usage
+fi
+
+if [ ! -z "$filename" ] && [ -z "$cmd" ]; then
+    error "If passing in a file, a command must also be used"
+    usage
+fi
+
+if [ "$cmd" == "queue" ]; then
+    echo "$filename" >> $queue
+    exit 0
+elif [ "$cmd" == "crop" ]; then
+    if [ -z "$option" ]; then
+        error "Crop requires a value"
+        usage
+    fi
+    echo "$3" > "$crops/$filename"
+    exit 0
+fi
 
 input="$(sed -n 1p "$queue")"
 
